# Generated by Django 4.2.6 on 2024-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dgt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=32)),
                ("app", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
