# Generated by Django 5.0.1 on 2024-02-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgt', '0002_apptester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppTester',
        ),
    ]
